# Generated by Django 4.2.7 on 2024-04-30 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0003_alter_document_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='user_id',
            new_name='user',
        ),
    ]
