# Generated by Django 4.2.7 on 2024-04-30 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0004_rename_user_id_document_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='user',
            new_name='user_id',
        ),
    ]
