# Generated by Django 4.2.7 on 2024-04-02 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='course_id',
        ),
    ]
