# Generated by Django 4.2.7 on 2024-04-05 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_user_name'),
        ('Course', '0003_alter_bookmark_document_id_alter_bookmark_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='ManyUser',
        ),
        migrations.AddField(
            model_name='course',
            name='User',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='authentication.user'),
        ),
    ]
