# Generated by Django 4.2.6 on 2024-04-05 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0005_rename_user_course_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='User_id',
            new_name='user_id',
        ),
    ]
