# Generated by Django 5.0 on 2024-04-05 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0006_rename_user_id_course_user_id'),
        ('authentication', '0003_remove_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='authentication.user'),
        ),
    ]
