# Generated by Django 4.2.7 on 2024-04-05 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_remove_user_name'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quizz',
            fields=[
                ('quizz_id', models.AutoField(primary_key=True, serialize=False)),
                ('quizz_name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=6, unique=True)),
                ('ManyUser', models.ManyToManyField(related_name='quizz', to='authentication.user')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
