# Generated by Django 5.0.3 on 2024-03-25 08:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quizz", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quizz",
            name="question_id",
        ),
    ]
