# Generated by Django 5.0 on 2024-05-15 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_user_name'),
        ('quizz', '0002_remove_quizz_manyuser_quizz_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizz',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user'),
        ),
    ]
