# Generated by Django 4.2.6 on 2024-04-03 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizz', '0001_initial'),
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='quizz_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizz.quizz'),
        ),
    ]
