# Generated by Django 5.0 on 2024-05-15 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='quizz_id',
            new_name='quizz',
        ),
    ]
