# Generated by Django 5.0.3 on 2024-03-24 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("QandA", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="listOfAnswers",
            fields=[
                ("answer_id", models.AutoField(primary_key=True, serialize=False)),
                ("answer", models.CharField(max_length=255)),
                (
                    "question_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="QandA.qanda"
                    ),
                ),
            ],
        ),
    ]
