# Generated by Django 4.2.6 on 2024-04-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('chapter_id', models.AutoField(primary_key=True, serialize=False)),
                ('chapter_name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('code', models.CharField(max_length=6, unique=True)),
            ],
        ),
    ]
