# Generated by Django 4.2.6 on 2024-04-05 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0001_initial'),
        ('Chapter', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='quizz_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='quizz.quizz'),
        ),
    ]
