# Generated by Django 5.0.3 on 2024-03-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QandA",
            fields=[
                ("question_id", models.IntegerField(primary_key=True, serialize=False)),
                ("question", models.TextField()),
                ("answer", models.CharField(max_length=255)),
            ],
        ),
    ]
