# Generated by Django 5.0.3 on 2024-03-25 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("QandA", "0002_qanda_delete_qa"),
        ("quizz", "0002_remove_quizz_question_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="QandA",
            fields=[
                ("question_id", models.AutoField(primary_key=True, serialize=False)),
                ("question", models.TextField()),
                ("answer", models.CharField(max_length=255)),
                (
                    "quizz_id",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quizz.quizz",
                    ),
                ),
            ],
        ),
    ]
