# Generated by Django 4.2.6 on 2024-04-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerList',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer1', models.CharField(max_length=255)),
                ('answer2', models.CharField(max_length=255)),
                ('answer3', models.CharField(max_length=255)),
            ],
        ),
    ]
